name: test sync
run-name: ${{ github.actor }} test sync.
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
jobs:
  verify-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.15.0'
      - run: echo "hello world"