name: install-and-test-inula
run-name: ${{ github.actor }} does install and test cases.
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master
jobs:
  verify-test-cases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.15.0'
      - run: npm install -g pnpm
      - run: npm list -g
      - run: npm install --force
      - run: cd packages/inula && ls && npm test -- --coverage && ls
        continue-on-error: true
      - run: cd packages/inula && ls
      - run: cd packages/inula-intl && ls && npm test -- --coverage && ls
        continue-on-error: true
      - run: cd packages/inula-intl && ls
      - run: cd packages/inula-request && ls && npm test -- --coverage && ls
        continue-on-error: true
      - run: cd packages/inula-request && ls 
      - run: cd packages/inula-router && ls && npm test -- --coverage && ls
        continue-on-error: true
      - run: cd packages/inula-router && ls
      - run: npm run test:inula
        continue-on-error: true
      - run: npm run lint
        continue-on-error: true