name: Docker Image CI/CD
run-name: ${{ github.actor }} push image to dockerhub.
on:
  workflow_run:
    workflows: ["Release"] # run after build and test workflow
    types:
      - completed
jobs:
  # 构建并上传 Docker镜像
  build: 
    runs-on: ubuntu-latest # 依赖的环境      
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          docker build -t newplayertp/inula -f Dockerfile .
      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Image
        run: |
          docker push newplayertp/inula